### ISSUE TITLE
Proposal - Support IP2Location.io API as Data Source

### ISSUE THREAD

**Issue by ip2location-com** [ohh-haolin/ipaddress-cfworker#1]
Hi @attr0,

We would like introduce IP2Location.io IP geolocation API which is one of the fastest API in the industry using CDN edges.

It is available in Free plan with free 30,000 queries per month and working fine under CF workers (tested).

You can visit our web site https://www.ip2location.io for more information including the documentation.

Kindly let us know if you have any question.

**Comment by ip2location-com** [comment]
We have posted a PR. Feel free to let us know if it is working fine or not.

**Comment by attr0** [comment]
Many thanks! The merge request is accepted.
